"""Type stubs for the native `_datapress_client` extension module."""

from __future__ import annotations

class DataPressError(Exception):
    """Raised when a DataPress request fails."""

class Client:
    def __init__(
        self,
        base_url: str,
        *,
        api_base: str | None = ...,
        admin_token: str | None = ...,
        bearer_token: str | None = ...,
        timeout_secs: float | None = ...,
    ) -> None: ...
    def healthz(self) -> str: ...
    def readyz(self) -> str: ...
    def datasets(self) -> list[str]: ...
    def schema(self, dataset: str) -> str: ...
    def count(self, dataset: str, predicates_json: str | None = ...) -> int: ...
    def query_json(self, dataset: str, request_json: str) -> str: ...
    def query_arrow(self, dataset: str, request_json: str) -> bytes: ...
    def sql(self, sql: str, max_rows: int | None = ...) -> str: ...
    def reload(self, dataset: str) -> str: ...
