#!/bin/sh
# Regenerate the Homebrew formula for a given datapress release.
#
# Usage:
#   packaging/homebrew/update-formula.sh <version> <out-file>
#
# <version> is the bare semver (e.g. 0.4.4), <out-file> is where the
# Formula/datapress.rb contents are written. The script downloads the three
# Unix release archives for that version and computes their SHA-256 sums, so
# it must be run after the release assets are published.
set -eu

VERSION="${1:?usage: update-formula.sh <version> <out-file>}"
OUT="${2:?usage: update-formula.sh <version> <out-file>}"
REPO="jeroenflvr/datapress"
BASE="https://github.com/${REPO}/releases/download/v${VERSION}"

sha_for() {
    # sha_for <target-triple-suffix>
    _f="datapress-v${VERSION}-$1.tar.gz"
    _tmp="$(mktemp)"
    curl -sSfL -o "$_tmp" "${BASE}/${_f}"
    if command -v sha256sum >/dev/null 2>&1; then
        sha256sum "$_tmp" | awk '{print $1}'
    else
        shasum -a 256 "$_tmp" | awk '{print $1}'
    fi
    rm -f "$_tmp"
}

SHA_MAC_ARM="$(sha_for aarch64-apple-darwin)"
SHA_LINUX_ARM="$(sha_for aarch64-unknown-linux-gnu)"
SHA_LINUX_X64="$(sha_for x86_64-unknown-linux-gnu)"

cat > "$OUT" <<EOF
# Homebrew formula for the prebuilt \`datapress\` CLI.
#
# Generated by packaging/homebrew/update-formula.sh — do not edit by hand.
# Installs the standalone binary (both DuckDB + DataFusion backends bundled)
# from the GitHub release; it does NOT compile from source.
class Datapress < Formula
  desc "Fast multi-backend (DuckDB / DataFusion) HTTP server over Parquet and Delta"
  homepage "https://datap-rs.org"
  version "${VERSION}"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/jeroenflvr/datapress/releases/download/v#{version}/datapress-v#{version}-aarch64-apple-darwin.tar.gz"
      sha256 "${SHA_MAC_ARM}"
    end
    on_intel do
      odie "datapress has no prebuilt Intel macOS binary. Install with: cargo install datapress"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/jeroenflvr/datapress/releases/download/v#{version}/datapress-v#{version}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "${SHA_LINUX_ARM}"
    end
    on_intel do
      url "https://github.com/jeroenflvr/datapress/releases/download/v#{version}/datapress-v#{version}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "${SHA_LINUX_X64}"
    end
  end

  def install
    bin.install "datapress"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/datapress --version")
  end
end
EOF

echo "Wrote $OUT for datapress v${VERSION}"
